src/Entity/Bonus.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BonusRepository")
 */
class Bonus
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dzial;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nazwa;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $EAN;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cena;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $minLiczbaSztuk;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prowizja;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $poprzedniaCena;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $poprzedniaProwizja;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $komentarzCena;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $komentarzProwizja;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDzial(): ?string
    {
        return $this->dzial;
    }

    public function setDzial(string $dzial): self
    {
        $this->dzial = $dzial;

        return $this;
    }

    public function getNazwa(): ?string
    {
        return $this->nazwa;
    }

    public function setNazwa(string $nazwa): self
    {
        $this->nazwa = $nazwa;

        return $this;
    }

    public function getEAN(): ?string
    {
        return $this->EAN;
    }

    public function setEAN(string $EAN): self
    {
        $this->EAN = $EAN;

        return $this;
    }

    public function getCena(): ?string
    {
        return $this->cena;
    }

    public function setCena(string $cena): self
    {
        $this->cena = $cena;

        return $this;
    }

    public function getMinLiczbaSztuk(): ?string
    {
        return $this->minLiczbaSztuk;
    }

    public function setMinLiczbaSztuk(string $minLiczbaSztuk): self
    {
        $this->minLiczbaSztuk = $minLiczbaSztuk;

        return $this;
    }

    public function getProwizja(): ?string
    {
        return $this->prowizja;
    }

    public function setProwizja(string $prowizja): self
    {
        $this->prowizja = $prowizja;

        return $this;
    }

    public function getPoprzedniaCena(): ?string
    {
        return $this->poprzedniaCena;
    }

    public function setPoprzedniaCena(string $poprzedniaCena): self
    {
        $this->poprzedniaCena = $poprzedniaCena;

        return $this;
    }

    public function getPoprzedniaProwizja(): ?string
    {
        return $this->poprzedniaProwizja;
    }

    public function setPoprzedniaProwizja(string $poprzedniaProwizja): self
    {
        $this->poprzedniaProwizja = $poprzedniaProwizja;

        return $this;
    }

    public function getKomentarzCena(): ?string
    {
        return $this->komentarzCena;
    }

    public function setKomentarzCena(string $komentarzCena): self
    {
        $this->komentarzCena = $komentarzCena;

        return $this;
    }

    public function getKomentarzProwizja(): ?string
    {
        return $this->komentarzProwizja;
    }

    public function setKomentarzProwizja(string $komentarzProwizja): self
    {
        $this->komentarzProwizja = $komentarzProwizja;

        return $this;
    }
}

src/Form/AllegroType.php
<?php

namespace App\Form;

use App\Entity\AllegroCSV;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AllegroType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('allegro', FileType::class,[
                'mapped'=>false,
                'label'=>'Please upload a favorite image'
            ])
            ->add('startDate', DateType::class,[

            ])
            ->add('endDate', DateType::class,[

            ])
            ->add('Submit', SubmitType::class,[
                'attr'=>[
                    'class'=>'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AllegroCSV::class,
        ]);
    }
}

src/Controller/AllegroController.php
<?php

namespace App\Controller;

use App\Entity\AllegroCSV;
use App\Entity\Bonus;
use App\Form\AllegroType;
use App\Repository\AllegroCSVRepository;
use App\Repository\BonusRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use League\Csv\Reader;
use League\Csv\Statement;
use League\Csv\CharsetConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AllegroController extends AbstractController
{

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    /**
     * @Route("/allegro", name="allegro")
     */
    public function index(AllegroCSVRepository $allegroCSVRepository, BonusRepository $bonusRepository)
    {

        return $this->render('allegro/index.html.twig', [
            'controller_name' => 'AllegroController',
            'allegro'=>$allegroCSVRepository->findAll(),
            'bonusik'=>$bonusRepository->findAll()
        ]);
    }


    /**
     * @Route("/allegro/new", name="allegroNew")
     */
    public function newAllegro(Request $request)
    {
        $allegro = new AllegroCSV();
        $form = $this->createForm(AllegroType::class, $allegro);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $info = pathinfo($_FILES['allegro']['name']['allegro']);

            if($info['extension'] == 'csv'){
                $file = $request->files->get('allegro')['allegro'];
                //$originalName = $_FILES['allegro']['name'];

                $uploads_directory = $this->getParameter('uploads_directory');
                $allegro->setDirectory($uploads_directory);

                $file_name = $_FILES['allegro']['name']['allegro'];
                $allegro->setFileName($file_name);

                $file->move(
                    $uploads_directory,
                    $file_name
                );

                $em = $this->getDoctrine()->getManager();
                $em->persist($allegro);
                $em->flush();
                $this->addFlash(
                    'info',
                    'Added Successfull!!!'
                );

/////////////////////////////////////////
                $directory = 'D:\Programy\xampp\htdocs\symfony\practice/public/uploads/Allegro (1).csv.txt';


                $reader = Reader::createFromPath($uploads_directory.'/'.$file_name,'r');
                $reader->setHeaderOffset(2);
                //$result = $reader->fetchColumn();

                $input_bom = $reader->getInputBOM();
                if ($input_bom === Reader::BOM_UTF16_LE || $input_bom === Reader::BOM_UTF16_BE) {
                    CharsetConverter::addTo($reader, 'utf-16', 'utf-8');
                }

                $stmt = (new Statement())
                    ->offset(10)
                    ->limit(25);

                $result = $stmt->process($reader);
                echo"<pre>";
                var_dump($result);



                foreach ($reader as $row){
                    $bonus = (new Bonus())
                        ->setDzial($row[0])
                        ->setNazwa($row[1])
                        ->setEAN($row[2])
                        ->setCena($row[3])
                        ->setMinLiczbaSztuk($row[4])
                        ->setProwizja($row[5])
                        ->setPoprzedniaCena($row[6])
                        ->setPoprzedniaProwizja($row[7])
                        ->setKomentarzCena($row[8])
                        ->setKomentarzProwizja($row[9])
                    ;


                    $this->em->persist($bonus);
                }
                $this->em->flush();

///////////////////////////////////////


                return $this->redirectToRoute('allegro');
            }else{
                $this->addFlash(
                    'info',
                    'Wrong file extension, should be a .csv!!!'
                );
                return $this->redirectToRoute('allegro');
            }

        }


        return $this->render('allegro/new.html.twig', [
            'allegro_form' => $form->createView()
        ]);
    }
}

templates/allegro/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AllegroController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
    {% for message in app.flashes('info') %}
        <div class="alert alert-info">
            {{ message }}
        </div>
    {% endfor %}

    {% for all in allegro %}
    <table class="table table-stripped">
        <tr>
            <td> {{ all.name }} </td>
            <td> {{ all.startDate|date("Y/m/d") }} </td>
            <td> {{ all.endDate|date("Y/m/d") }} </td>
            <td> {{ all.fileName }} </td>
            <td> {{ all.directory }} </td>
        </tr>
    </table>
    {% endfor %}


    <h1>Program bonusowy - Prowizja nawet 0,5% - Allegro</h1>

    <div class="container">
        <table class="table table-stripped">
            <thead>
            <tr>
                <td>dzial</td>
                <td>nazwa</td>
                <td>ean</td>
                <td>cena</td>
                <td>min_liczba_sztuk</td>
                <td>prowizja</td>
                <td>poprzednia_cena</td>
                <td>poprzednia_prowizja</td>
                <td>komentarz_cena</td>
                <td>komentarz_prowizja</td>
            </tr>
            </thead>
            <tbody>
            {% for bonus in bonusik %}
            <tr>
                <td>{{ bonus.dzial }}</td>
                <td>{{ bonus.nazwa }}</td>
                <td>{{ bonus.eAN }}</td>
                <td>{{ bonus.cena }}</td>
                <td>{{ bonus.minLiczbaSztuk }}</td>
                <td>{{ bonus.prowizja }}</td>
                <td>{{ bonus.poprzedniaCena }}</td>
                <td>{{ bonus.poprzedniaProwizja }}</td>
                <td>{{ bonus.komentarzCena }}</td>
                <td>{{ bonus.komentarzProwizja }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

<div class="example-wrapper">

</div>
{% endblock %}

templates/allegro/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AllegroController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
    <h1 class="text-center">Allegro CSV Form:</h1>

<div class="example-wrapper">
    {{ form_start(allegro_form) }}
        {{ form_widget(allegro_form) }}
    {{ form_end(allegro_form) }}
</div>
{% endblock %}